services:
  auction-test:
    extends:
      file: compose.base.yaml
      service: auction
    build:
      target: test
    environment:
      - spring_profiles_active=test
    depends_on:
      - test-db
  test-db:
    extends:
      file: compose.base.yaml
      service: db
